### ISSUE TITLE
Unable to specify property = "web"

### ISSUE THREAD

**Issue by lbrandt** [racorreia/gtrendsAPI#1]
When I call `gtrendsAPI::getGraph` with arguments, I cannot actually set `property = "web"`. When I try, it fails with the following error: `! property must be one of "images", "news", "froogle" or "youtube". Defaults to "web".`

That is because `gtrendsAPI::properties` does not contain "web" itself. And the code for getGraph does not actually set the default despite what the error message claims. 

If you prefer I'm happy to do a PR. Great package in any case!

**Comment by racorreia** [comment]
Hi @lbrandt,

Sorry for the slow reply, which was due to the holiday season.

Thank you for spotting this issue, which can be easily fixed. Also, you are right that the message is unclear, it should read "Defaults to "web" when unspecified". 

I'll be submitting a fix for both issues later today or tomorrow. Will post a new comment and close the issue when the package is updated.

Many thanks for the positive feedback!

**Comment by racorreia** [comment]
Just a quick update on this issue to mention that I've submitted changes to the package that resolve this issue. Thank you @lbrandt for bringing this to my attention.
